import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>BascoTest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <br />
      <br />
      <br />
      <div className='container'>
        <h1>Bienvenue sur Code.io</h1>
        <p>Le blog communautaire des afficionados du développement Web.</p>
        <br />
        <br />
        <br />
        <div className='row'>
          <div className="col" >
            <div className="card-body">
              <h5 className="card-title">Lisez les articles</h5>
              <p className="card-text">
                Maximiser votre culture Web <br />
                Chaque auteur tente de vous apportez le plus de valeur possible par article.</p>
                <Link href="/blog">
                  <a>Visitez le blog</a>
                </Link>
            </div>

          </div><div className="col">
            <div className="card-body">
              <h5 className="card-title">Faite un tour vers la liste des membres</h5>
              <p className="card-text">
                Faites vous des amis <br />
                Ajoutez, invitez et discutez avec les différents membres.
              </p>
              <Link href="/liste">
                <a>Découvrez la liste de nos membres</a>
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}